export const MAX_COMPETITOR_DISCOVERY_PROSPECTS_PER_RUN = 5;

export const MAX_COMPETITOR_PROVIDER_REQUESTS_PER_PROSPECT = 3;

export const MAX_COMPETITOR_CANDIDATES_PER_PROSPECT = 10;

export const MAX_SELECTED_COMPETITORS_PER_PROSPECT = 3;

export const COMPETITOR_DISCOVERY_CONCURRENCY = 2;

export const COMPETITOR_DISCOVERY_TTL_MS = 30 * 24 * 60 * 60 * 1000;

export const STALE_COMPETITOR_DISCOVERY_RUN_MS = 12 * 60 * 1000;

export const COMPETITOR_PROVIDER_GOOGLE_PLACES = "GOOGLE_PLACES";

export const DEFAULT_COMPETITOR_RADIUS_MILES = 25;
