import { AI_GENERATION_TIMEOUT_MS } from "@/lib/website-audit/ai-interpretation/constants";

export const IMPLEMENTATION_INTERPRETATION_VERSION = 1;
export const IMPLEMENTATION_INTERPRETATION_PROMPT_VERSION = 1;

export const MAX_IMPLEMENTATION_INTERPRETATIONS_PER_ACTION = 1;
export const MAX_IMPLEMENTATION_INTERPRETATION_REPAIR_ATTEMPTS = 1;
export const IMPLEMENTATION_INTERPRETATION_CONCURRENCY = 1;

export const MAX_AI_IMPLEMENTATION_WORKSTREAMS = 7;
export const MAX_AI_ACTIONS_PER_WORKSTREAM = 6;
export const MAX_AI_EVIDENCE_PER_WORKSTREAM = 8;
export const MAX_AI_PRESERVATION_CONSTRAINTS = 4;
export const MAX_AI_SEQUENCING_PHASES = 3;
export const MAX_AI_IMPLEMENTATION_CONSIDERATIONS = 6;
export const MAX_AI_TALKING_POINTS = 6;

export const MAX_EXECUTIVE_HEADLINE_CHARS = 120;
export const MAX_EXECUTIVE_SUMMARY_CHARS = 1_200;
export const MAX_APPROACH_CHARS = 1_200;
export const MAX_WORKSTREAM_EXPLANATION_CHARS = 700;
export const MAX_BUSINESS_RATIONALE_CHARS = 600;
export const MAX_ACTION_EXPLANATION_CHARS = 400;
export const MAX_PRESERVATION_NOTE_CHARS = 400;
export const MAX_PHASE_EXPLANATION_CHARS = 800;
export const MAX_CONSIDERATION_TITLE_CHARS = 160;
export const MAX_CONSIDERATION_EXPLANATION_CHARS = 600;
export const MAX_TALKING_POINT_CHARS = 280;
export const MAX_PHASE_LABEL_CHARS = 80;
export const MAX_CLIENT_TITLE_CHARS = 160;

export const IMPLEMENTATION_INTERPRETATION_TIMEOUT_MS = AI_GENERATION_TIMEOUT_MS;
